// Generated by scripts/build.mjs. HTML uses the network first so reopening gets updates.
const CACHE = "nutrition-v14-app-TI6NNILE";
const ASSETS = ["./index.html","./manifest.webmanifest","./icon-180.png","./icon-192.png","./icon-512.png","./assets/app-TI6NNILE.js","./assets/shared-35HBSXCP.js"];
self.addEventListener('install', event => {
  event.waitUntil(caches.open(CACHE).then(cache => cache.addAll(ASSETS)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', event => {
  event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(key => (key.startsWith('nutrition-v') || key === 'kbju-trainer-v1') && key !== CACHE).map(key => caches.delete(key)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', event => {
  const url = new URL(event.request.url);
  if (event.request.method !== 'GET' || url.origin !== self.location.origin || !url.href.startsWith(self.registration.scope)) return;
  if (event.request.mode === 'navigate') {
    event.respondWith((async () => {
      const cache = await caches.open(CACHE);
      const index = new URL('./index.html', self.registration.scope).href;
      try {
        const response = await fetch(event.request, { cache: 'no-cache' });
        if (response.ok) await cache.put(index, response.clone()).catch(() => {});
        return response;
      } catch (error) {
        const cached = await cache.match(index);
        if (cached) return cached;
        throw error;
      }
    })());
  } else {
    event.respondWith((async () => {
      const cache = await caches.open(CACHE);
      const cached = await cache.match(event.request);
      if (cached) return cached;
      const response = await fetch(event.request);
      if (response.ok && (url.pathname.includes('/assets/') || ASSETS.some(asset => new URL(asset, self.registration.scope).href === url.href))) await cache.put(event.request, response.clone()).catch(() => {});
      return response;
    })());
  }
});
