import { build } from 'esbuild';
import { readFile, mkdir, writeFile, rm } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const result = await build({ entryPoints: [path.join(root, 'src/App.jsx')], bundle: true, write: false,
  minify: true, legalComments: 'inline', charset: 'utf8', target: ['es2020'], format: 'iife', define: { 'process.env.NODE_ENV': '"production"' } });
const css = await readFile(path.join(root, 'src/styles.css'), 'utf8');
const js = result.outputFiles[0].text.replace(/<\/script/gi, '<\\/script');
const html = `<!DOCTYPE html>
<html lang="ru"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<meta name="theme-color" content="#09090b"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-title" content="Дневник питания">
<meta name="description" content="Питание и прогресс: КБЖУ, избранные продукты, готовые блюда, замеры тела и графики по дням.">
<title>Дневник питания</title><style>${css}</style></head><body><div id="root"></div><noscript>Для работы дневника включите JavaScript в браузере.</noscript><script>${js}</script></body></html>`;
await mkdir(path.join(root, 'dist'), { recursive: true });
const web = await build({ entryPoints: { app: path.join(root, 'src/App.jsx'), vendor: path.join(root, 'src/vendor.mjs') },
  bundle: true, splitting: true, format: 'esm', outdir: path.join(root, 'assets'), write: false,
  minify: true, legalComments: 'inline', charset: 'utf8', target: ['es2020'],
  entryNames: '[name]-[hash]', chunkNames: 'shared-[hash]', define: { 'process.env.NODE_ENV': '"production"' } });
const appFile = web.outputFiles.find(file => path.basename(file.path).startsWith('app-'));
// Keep previously published hashed modules available for cached pages during updates.
await rm(path.join(root, 'dist/assets'), { recursive: true, force: true });
await mkdir(path.join(root, 'assets'), { recursive: true });
await mkdir(path.join(root, 'dist/assets'), { recursive: true });
for (const file of web.outputFiles) {
  const name = path.basename(file.path);
  if (name.startsWith('vendor-')) continue; // Only the shared module is loaded by the application.
  await writeFile(path.join(root, 'assets', name), file.contents);
  await writeFile(path.join(root, 'dist/assets', name), file.contents);
}
const workerRegistration = `<script>if('serviceWorker' in navigator && location.protocol !== 'file:'){window.addEventListener('load',function(){navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).then(function(registration){registration.update().catch(function(){});}).catch(function(){});});}</script>`;
const hostedHtml = html.slice(0, html.indexOf('<script>')) + `<script type="module" src="./assets/${path.basename(appFile.path)}"></script>${workerRegistration}</body></html>`;
const hostedWithIcons = hostedHtml.replace('</head>', '<link rel="apple-touch-icon" sizes="180x180" href="icon-180.png"><link rel="icon" type="image/png" sizes="192x192" href="icon-192.png"><link rel="manifest" href="manifest.webmanifest"></head>');
await writeFile(path.join(root, 'index.html'), hostedWithIcons);
await writeFile(path.join(root, 'dist/index.html'), hostedWithIcons);
await writeFile(path.join(root, 'Дневник-питания.html'), html);
const shellAssets = ['./index.html', './manifest.webmanifest', './icon-180.png', './icon-192.png', './icon-512.png', ...web.outputFiles.filter(file => !path.basename(file.path).startsWith('vendor-')).map(file => `./assets/${path.basename(file.path)}`)];
const worker = `// Generated by scripts/build.mjs. HTML uses the network first so reopening gets updates.
const CACHE = ${JSON.stringify(`nutrition-v13-${path.basename(appFile.path, '.js')}`)};
const ASSETS = ${JSON.stringify(shellAssets)};
self.addEventListener('install', event => {
  event.waitUntil(caches.open(CACHE).then(cache => cache.addAll(ASSETS)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', event => {
  event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(key => (key.startsWith('nutrition-v') || key === 'kbju-trainer-v1') && key !== CACHE).map(key => caches.delete(key)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', event => {
  const url = new URL(event.request.url);
  if (event.request.method !== 'GET' || url.origin !== self.location.origin || !url.href.startsWith(self.registration.scope)) return;
  if (event.request.mode === 'navigate') {
    event.respondWith((async () => {
      const cache = await caches.open(CACHE);
      const index = new URL('./index.html', self.registration.scope).href;
      try {
        const response = await fetch(event.request, { cache: 'no-cache' });
        if (response.ok) await cache.put(index, response.clone()).catch(() => {});
        return response;
      } catch (error) {
        const cached = await cache.match(index);
        if (cached) return cached;
        throw error;
      }
    })());
  } else {
    event.respondWith((async () => {
      const cache = await caches.open(CACHE);
      const cached = await cache.match(event.request);
      if (cached) return cached;
      const response = await fetch(event.request);
      if (response.ok && (url.pathname.includes('/assets/') || ASSETS.some(asset => new URL(asset, self.registration.scope).href === url.href))) await cache.put(event.request, response.clone()).catch(() => {});
      return response;
    })());
  }
});
`;
await writeFile(path.join(root, 'sw.js'), worker);
await writeFile(path.join(root, 'dist/sw.js'), worker);
console.log(`Ready: index.html + Дневник-питания.html (${Math.round(Buffer.byteLength(html) / 1024)} KB), no CDN dependencies.`);
